# Setup
title:        Jessica Deaton
tagline:      Developer, Project Manager, Product Owner, Human
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Jessica Deaton
  url:        http://jessicadeaton.com 


twitter_username: __deatz__
github_username: deatonjm
linkedin_username: jessica-deaton
email: jessicadeaton@outlook.com


include:
  - _pages


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
